;Display handle
(define *handle-device* (get-handle-view-dc))
(define *handle-window* (get-handle-view-wnd))

;DLL handle
(define *handle-dll-gdi32* (load-library "Gdi32.dll"))
(define *handle-dll-kernel32* (load-library "Kernel32.dll"))
(define *handle-dll-user32* (load-library "User32.dll"))

;system
(define sleep (lambda (millisec) (call-library *handle-dll-kernel32* "Sleep" millisec)))
(define beep (lambda (freq millisec) (call-library *handle-dll-kernel32* "Beep" freq millisec)))
(define cd (lambda (dir) (call-library *handle-dll-kernel32* "SetCurrentDirectoryA" dir)))

(define allocconsole (lambda () (call-library *handle-dll-kernel32* "AllocConsole")))
(define freeconsole (lambda () (call-library *handle-dll-kernel32* "FreeConsole")))
(define getconsoletitle (lambda (inptitle size) (call-library *handle-dll-kernel32* "GetConsoleTitle" inptitle size)))
(define findwindow (lambda (classname windowname) (call-library *handle-dll-user32* "FindWindow" classname windowname)))
(define showwindow (lambda (hwnd cmd) (call-library *handle-dll-user32* "ShowWindow" hwnd cmd)))
; * ShowWindow() Commands
(define SW_HIDE             0)
(define SW_SHOWNORMAL       1)
(define SW_NORMAL           1)
(define SW_SHOWMINIMIZED    2)
(define SW_SHOWMAXIMIZED    3)
(define SW_MAXIMIZE         3)
(define SW_SHOWNOACTIVATE   4)
(define SW_SHOW             5)
(define SW_MINIMIZE         6)
(define SW_SHOWMINNOACTIVE  7)
(define SW_SHOWNA           8)
(define SW_RESTORE          9)
(define SW_SHOWDEFAULT      10)
(define SW_FORCEMINIMIZE    11)
(define SW_MAX              11)

; * Old ShowWindow() Commands
(define HIDE_WINDOW         0)
(define SHOW_OPENWINDOW     1)
(define SHOW_ICONWINDOW     2)
(define SHOW_FULLSCREEN     3)
(define SHOW_OPENNOACTIVATE 4)

; * Identifiers for the WM_SHOWWINDOW message
(define SW_PARENTCLOSING    1)
(define SW_OTHERZOOM        2)
(define SW_PARENTOPENING    3)
(define SW_OTHERUNZOOM      4)


(define getstdhandle (lambda (stdhandle) (call-library *handle-dll-kernel32* "GetStdHandle" stdhandle)))
(define STD_INPUT_HANDLE   -10)
(define STD_OUTPUT_HANDLE  -11)
(define STD_ERROR_HANDLE   -12)

;graphics
(define lineto (lambda (hdc x y) (call-library *handle-dll-gdi32* "LineTo" hdc x y)))
(define moveto (lambda (hdc x y) (call-library *handle-dll-gdi32* "MoveToEx" hdc x y 0)))

(define invalidaterect (lambda (hwnd rect erase) (call-library *handle-dll-user32* "InvalidateRect" hwnd rect erase)))
(define updatewindow (lambda (hwnd) (call-library *handle-dll-user32* "UpdateWindow" hwnd)))

(define flush-window (lambda (hwnd)
  (invalidaterect hwnd 0 1)
  (updatewindow hwnd)))

(define textout (lambda (hdc x y str len) (call-library *handle-dll-gdi32* "TextOutA" hdc x y str len)))
(define settextcolor (lambda (hdc color) (call-library *handle-dll-gdi32* "SetTextColor" hdc color)))
(define setbkcolor (lambda (hdc color) (call-library *handle-dll-gdi32* "SetBkColor" hdc color)))
(define rgb (lambda (r g b) (+ r (* g 256) (* b 65536))))	;ビットシフトってどうやんの？
(define selectobject (lambda (hdc hobj) (call-library *handle-dll-gdi32* "SelectObject" hdc hobj)))
;
(define getdc (lambda (hwnd) (call-library *handle-dll-user32* "GetDC" hwnd)))
(define releasedc (lambda (hwnd hdc) (call-library *handle-dll-user32* "ReleaseDC" hwnd hdc)))
(define createcompatiblebitmap (lambda (hdc cx cy) (call-library *handle-dll-gdi32* "CreateCompatibleBitmap" hdc cx cy)))
(define selectobject (lambda (hdc bmp) (call-library *handle-dll-gdi32* "SelectObject" hdc bmp)))
(define deletedc (lambda (hdc) (call-library *handle-dll-gdi32* "DeleteDC" hdc)))

(define getclientrect (lambda (hwnd lprect) (call-library *handle-dll-user32* "GetClientRect" hwnd lprect)))
(define getwindowrect (lambda (hwnd lprect) (call-library *handle-dll-user32* "GetWindowRect" hwnd lprect)))


;pen
(define create-pen (lambda (style width color) (call-library *handle-dll-gdi32* "CreatePen" style width color)))
(define delete-pen (lambda (hpen) (call-library *handle-dll-gdi32* "DeleteObject" pen)))
(define select-pen (lambda (hpen) (selectobject hpen)))
;pen style
(define PS-SOLID            0)	;実線
(define PS-DASH             1)	;破線
(define PS-DOT              2)	;点線
(define PS-DASHDOT          3)	;一点鎖線
(define PS-DASHDOTDOT       4)	;二点鎖線
(define PS-NULL             5)	;空
(define PS-INSIDEFRAME      6)	;実線

;ex
;;(settextcolor (rgb 0 #xFF #xFF))
;;(define hpen (create-pen 1 5 (rgb #xFF 0 #xFF)))
;;(select-pen hpen)


;key
(define scan-key (lambda (key) (call-library *handle-dll-user32* "GetKeyState" key)))

;keydefine
;mouse
(define VK-LBUTTON #x01)
(define VK-RBUTTON #x02)
(define VK-CANCEL #x03)
(define VK-MBUTTON #x04)
(define VK-XBUTTON1 #x05)
(define VK-XBUTTON2 #x06)
;keyboard
(define VK-BACK #x08)
(define VK-TAB #x09)
(define VK-CLEAR #x0C)
(define VK-RETURN #x0D)
(define VK-SHIFT #x10)
(define VK-CONTROL #x11)
(define VK-MENU #x12)
(define VK-PAUSE #x13)
(define VK-CAPITAL #x14)
(define VK-KANA #x15)
(define VK-HANGEUL #x15)
(define VK-HANGUL #x15)
(define VK-JUNJA #x17)
(define VK-FINAL #x18)
(define VK-HANJA #x19)
(define VK-KANJI #x19)
(define VK-ESCAPE #x1B)
(define VK-CONVERT #x1C)
(define VK-NONCONVERT #x1D)
(define VK-ACCEPT #x1E)
(define VK-MODECHANGE #x1F)
(define VK-SPACE #x20)
(define VK-PRIOR #x21)
(define VK-NEXT #x22)
(define VK-END #x23)
(define VK-HOME #x24)
(define VK-LEFT #x25)
(define VK-UP #x26)
(define VK-RIGHT #x27)
(define VK-DOWN #x28)
(define VK-SELECT #x29)
(define VK-PRINT #x2A)
(define VK-EXECUTE #x2B)
(define VK-SNAPSHOT #x2C)
(define VK-INSERT #x2D)
(define VK-DELETE #x2E)
(define VK-HELP #x2F)
(define VK-LWIN #x5B)
(define VK-RWIN #x5C)
(define VK-APPS #x5D)
(define VK-SLEEP #x5F)
(define VK-NUMPAD0 #x60)
(define VK-NUMPAD1 #x61)
(define VK-NUMPAD2 #x62)
(define VK-NUMPAD3 #x63)
(define VK-NUMPAD4 #x64)
(define VK-NUMPAD5 #x65)
(define VK-NUMPAD6 #x66)
(define VK-NUMPAD7 #x67)
(define VK-NUMPAD8 #x68)
(define VK-NUMPAD9 #x69)
(define VK-MULTIPLY #x6A)
(define VK-ADD #x6B)
(define VK-SEPARATOR #x6C)
(define VK-SUBTRACT #x6D)
(define VK-DECIMAL #x6E)
(define VK-DIVIDE #x6F)
(define VK-F1 #x70)
(define VK-F2 #x71)
(define VK-F3 #x72)
(define VK-F4 #x73)
(define VK-F5 #x74)
(define VK-F6 #x75)
(define VK-F7 #x76)
(define VK-F8 #x77)
(define VK-F9 #x78)
(define VK-F10 #x79)
(define VK-F11 #x7A)
(define VK-F12 #x7B)
(define VK-F13 #x7C)
(define VK-F14 #x7D)
(define VK-F15 #x7E)
(define VK-F16 #x7F)
(define VK-F17 #x80)
(define VK-F18 #x81)
(define VK-F19 #x82)
(define VK-F20 #x83)
(define VK-F21 #x84)
(define VK-F22 #x85)
(define VK-F23 #x86)
(define VK-F24 #x87)
(define VK-NUMLOCK #x90)
(define VK-SCROLL #x91)
(define VK-OEM-NEC-EQUAL #x92)
(define VK-OEM-FJ-JISHO #x92)
(define VK-OEM-FJ-MASSHOU #x93)
(define VK-OEM-FJ-TOUROKU #x94)
(define VK-OEM-FJ-LOYA #x95)
(define VK-OEM-FJ-ROYA #x96)
(define VK-LSHIFT #xA0)
(define VK-RSHIFT #xA1)
(define VK-LCONTROL #xA2)
(define VK-RCONTROL #xA3)
(define VK-LMENU #xA4)
(define VK-RMENU #xA5)
(define VK-BROWSER-BACK #xA6)
(define VK-BROWSER-FORWARD #xA7)
(define VK-BROWSER-REFRESH #xA8)
(define VK-BROWSER-STOP #xA9)
(define VK-BROWSER-SEARCH #xAA)
(define VK-BROWSER-FAVORITES #xAB)
(define VK-BROWSER-HOME #xAC)
(define VK-VOLUME-MUTE #xAD)
(define VK-VOLUME-DOWN #xAE)
(define VK-VOLUME-UP #xAF)
(define VK-MEDIA-NEXT-TRACK #xB0)
(define VK-MEDIA-PREV-TRACK #xB1)
(define VK-MEDIA-STOP #xB2)
(define VK-MEDIA-PLAY-PAUSE #xB3)
(define VK-LAUNCH-MAIL #xB4)
(define VK-LAUNCH-MEDIA-SELECT #xB5)
(define VK-LAUNCH-APP1 #xB6)
(define VK-LAUNCH-APP2 #xB7)
(define VK-OEM-1 #xBA)
(define VK-OEM-PLUS #xBB)
(define VK-OEM-COMMA #xBC)
(define VK-OEM-MINUS #xBD)
(define VK-OEM-PERIOD #xBE)
(define VK-OEM-2 #xBF)
(define VK-OEM-3 #xC0)
(define VK-OEM-4 #xDB)
(define VK-OEM-5 #xDC)
(define VK-OEM-6 #xDD)
(define VK-OEM-7 #xDE)
(define VK-OEM-8 #xDF)
(define VK-OEM-AX #xE1)
(define VK-OEM-102 #xE2)
(define VK-ICO-HELP #xE3)
(define VK-ICO-00 #xE4)
(define VK-PROCESSKEY #xE5)
(define VK-ICO-CLEAR #xE6)
(define VK-PACKET #xE7)
(define VK-OEM-RESET #xE9)
(define VK-OEM-JUMP #xEA)
(define VK-OEM-PA1 #xEB)
(define VK-OEM-PA2 #xEC)
(define VK-OEM-PA3 #xED)
(define VK-OEM-WSCTRL #xEE)
(define VK-OEM-CUSEL #xEF)
(define VK-OEM-ATTN #xF0)
(define VK-OEM-FINISH #xF1)
(define VK-OEM-COPY #xF2)
(define VK-OEM-AUTO #xF3)
(define VK-OEM-ENLW #xF4)
(define VK-OEM-BACKTAB #xF5)
(define VK-ATTN #xF6)
(define VK-CRSEL #xF7)
(define VK-EXSEL #xF8)
(define VK-EREOF #xF9)
(define VK-PLAY #xFA)
(define VK-ZOOM #xFB)
(define VK-NONAME #xFC)
(define VK-PA1 #xFD)
(define VK-OEM-CLEAR #xFE)

(define VK-0 #x30)
(define VK-1 #x31)
(define VK-2 #x32)
(define VK-3 #x33)
(define VK-4 #x34)
(define VK-5 #x35)
(define VK-6 #x36)
(define VK-7 #x37)
(define VK-8 #x38)
(define VK-9 #x39)
(define VK-A #x41)
(define VK-B #x42)
(define VK-C #x43)
(define VK-D #x44)
(define VK-E #x45)
(define VK-F #x46)
(define VK-G #x47)
(define VK-H #x48)
(define VK-I #x49)
(define VK-J #x4A)
(define VK-K #x4B)
(define VK-L #x4C)
(define VK-M #x4D)
(define VK-N #x4E)
(define VK-O #x4F)
(define VK-P #x50)
(define VK-Q #x51)
(define VK-R #x52)
(define VK-S #x53)
(define VK-T #x54)
(define VK-U #x55)
(define VK-V #x56)
(define VK-X #x57)
(define VK-Y #x58)
(define VK-Z #x59)

;
; メニュー関連
;
(define loadmenu (lambda (hinstance lpmenuname) (call-library *handle-dll-user32* "LoadMenuA" hinstance lpmenuname)))
(define getwindowlong (lambda (hwnd param) (call-library *handle-dll-user32* "GetWindowLongA" hwnd param)))
(define setmenu (lambda (hwnd hmenu) (call-library *handle-dll-user32* "SetMenu" hwnd hmenu)))
(define getmenu (lambda (hwnd) (call-library *handle-dll-user32* "GetMenu" hwnd)))
(define getinstance (lambda (hwnd) (getwindowlong hwnd GWL-HINSTANCE)))	;インスタンスの取得
(define drawmenubar (lambda (hwnd) (call-library *handle-dll-user32* "DrawMenuBar" hwnd)))
(define createmenu (lambda () (call-library *handle-dll-user32* "CreateMenu")))
(define insertmenu (lambda (hmenu position flag item-or-hmenu newitem) (call-library *handle-dll-user32* "InsertMenuA" hmenu position flag item-or-hmenu newitem)))
(define createpopupmenu (lambda () (call-library *handle-dll-user32* "CreatePopupMenu")))

;ex
;(define hmenu (getmenu handle-window))
;(insertmenu hmenu 0 (+ MF-BYCOMMAND MF-STRING) 666 "inserttest")
;(insertmenu hmenu 32773 (+ MF-BYCOMMAND MF-STRING) 666 "inserttest(&D)")
;(insertmenu hmenu 666 (+ MF-BYCOMMAND MF-STRING) 667 "i667(&Y)")
;(drawmenubar)


; * Window field offsets for GetWindowLong()
;まだたくさんあるけどとりあえず
(define GWL-WNDPROC -4)
(define GWL-HINSTANCE -6)
(define GWL-HWNDPARENT -8)
(define GWL-STYLE -16)
(define GWL-EXSTYLE -20)
(define GWL-USERDATA -21)
(define GWL-ID -12)

;define insertMenu parameter
;/* ;win40  -- A lot of MF_* flags have been renamed as MFT_* and MFS_* flags */
;/*
; * Menu flags for Add/Check/EnableMenuItem()
; */
(define MF-INSERT           #x00000000)
(define MF-CHANGE           #x00000080)
(define MF-APPEND           #x00000100)
(define MF-DELETE           #x00000200)
(define MF-REMOVE           #x00001000)

(define MF-BYCOMMAND        #x00000000)
(define MF-BYPOSITION       #x00000400)

(define MF-SEPARATOR        #x00000800)

(define MF-ENABLED          #x00000000)
(define MF-GRAYED           #x00000001)
(define MF-DISABLED         #x00000002)

(define MF-UNCHECKED        #x00000000)
(define MF-CHECKED          #x00000008)
(define MF-USECHECKBITMAPS  #x00000200)

(define MF-STRING           #x00000000)
(define MF-BITMAP           #x00000004)
(define MF-OWNERDRAW        #x00000100)

(define MF-POPUP            #x00000010)
(define MF-MENUBARBREAK     #x00000020)
(define MF-MENUBREAK        #x00000040)

(define MF-UNHILITE         #x00000000)
(define MF-HILITE           #x00000080)

(define MF-DEFAULT          #x00001000)
(define MF-SYSMENU          #x00002000)
(define MF-HELP             #x00004000)
(define MF-RIGHTJUSTIFY     #x00004000)

(define MF-MOUSESELECT      #x00008000)		;;/* Obsolete -- only used by old RES files */
(define MF-END              #x00000080)


(define MFT-STRING          MF-STRING)
(define MFT-BITMAP          MF-BITMAP)
(define MFT-MENUBARBREAK    MF-MENUBARBREAK)
(define MFT-MENUBREAK       MF-MENUBREAK)
(define MFT-OWNERDRAW       MF-OWNERDRAW)
(define MFT-RADIOCHECK      #x00000200)
(define MFT-SEPARATOR       MF-SEPARATOR)
(define MFT-RIGHTORDER      #x00002000)
(define MFT-RIGHTJUSTIFY    MF-RIGHTJUSTIFY)

;;/* Menu flags for Add/Check/EnableMenuItem() */
(define MFS-GRAYED          #x00000003)
(define MFS-DISABLED        MFS-GRAYED)
(define MFS-CHECKED         MF-CHECKED)
(define MFS-HILITE          MF-HILITE)
(define MFS-ENABLED         MF-ENABLED)
(define MFS-UNCHECKED       MF-UNCHECKED)
(define MFS-UNHILITE        MF-UNHILITE)
(define MFS-DEFAULT         MF-DEFAULT)


